server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: exchange
          uri: http://localhost:8082
          predicates:
            - Path=/exchanges/**, 
        - id: point
          uri: http://localhost:8083
          predicates:
            - Path=/points/**, 
        - id: deadline
          uri: http://localhost:8084
          predicates:
            - Path=/deadlines/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: exchange
          uri: http://exchange:8080
          predicates:
            - Path=/exchanges/**, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: deadline
          uri: http://deadline:8080
          predicates:
            - Path=/deadlines/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
